# Generated by Django 3.1.2 on 2021-05-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210517_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
